from datetime import datetime, timezone
from .models import *
from .enums import *

T=datetime(2026,1,1,12,0,tzinfo=timezone.utc)

def all_objects_fixture():
    org=Organization('AlignAI HQ',id='org_001')
    person=Person('Executive',org.id,id='person_001')
    person2=Person('Assistant',org.id,id='person_002')
    role=Role('Executive Assistant',org.id,id='role_001')
    outcome=IntendedOutcome('Outcome',org.id,id='outcome_001',owner_id=person.id)
    condition=SuccessCondition('Success',outcome.id,id='condition_001')
    thread=OperationalThread(outcome.id,org.id,id='thread_001')
    resp=Responsibility(person2.id,'Follow-up',org.id,id='resp_001')
    work=WorkItem('Work',outcome.id,org.id,id='work_001',assignee_id=person2.id)
    work2=WorkItem('Dependent Work',outcome.id,org.id,id='work_002',assignee_id=person2.id)
    commitment=Commitment('Commitment',person2.id,org.id,id='commit_001')
    obligation=Obligation('Obligation','basis',person2.id,org.id,id='obligation_001')
    dep=Dependency(work.id,'work_002',RelationshipType.DEPENDS_ON,id='dep_001', envelope=ObjectEnvelope('dep_001','Dependency',organization_id=org.id))
    rel=Relationship(person.id,work.id,RelationshipType.OWNS,id='rel_001')
    event=Event('CREATED',T,'system',id='event_001',subject_id=work.id)
    evidence=Evidence('Evidence','source',T,id='evidence_001',subject_id=work.id)
    claim_old=Claim('Claim before correction',id='claim_old',status=ClaimStatus.SUPPORTED,supporting_evidence_ids=[evidence.id])
    claim=Claim('Claim corrected',id='claim_001',status=ClaimStatus.SUPPORTED,supporting_evidence_ids=[evidence.id])
    claim_old.envelope=ObjectEnvelope(**{**claim_old.envelope.__dict__,'created_at':T,'recorded_at':T})
    claim.envelope=ObjectEnvelope(**{**claim.envelope.__dict__,'created_at':T,'recorded_at':T})
    truth=TruthResolution(claim.id,ClaimStatus.SUPPORTED,'evidence',T,id='truth_001',supporting_evidence_ids=[evidence.id])
    state_prior=State(work.id,'DRAFT',id='state_prior',changed_at=datetime(2026,1,1,11,tzinfo=timezone.utc))
    state=State(work.id,'ACTIVE',id='state_001',previous_state_id=state_prior.id,changed_at=T,evidence_ids=[evidence.id])
    change=Change(work.id,'DRAFT','ACTIVE',T,id='change_001',basis_evidence_ids=[evidence.id],affected_object_ids=[work.id])
    consequence=Consequence(change.id,work.id,'work started','change',ConsequenceSupport.SUPPORTED,id='consequence_001',evidence_ids=[evidence.id])
    significance=SignificanceAssessment(consequence.id,'MEDIUM',['deadline'],T,id='significance_001')
    risk=Risk('Delay risk','MEDIUM',id='risk_001',related_object_ids=[work.id],evidence_ids=[evidence.id])
    intervention=Intervention(InterventionType.RECOMMEND,'risk',id='intervention_001',target_ids=[work.id])
    recommendation=Recommendation('Prioritize work','risk',id='recommendation_001',intervention_id=intervention.id)
    authority=AuthorityGrant(person.id,person2.id,'REQUEST_QUOTE',id='authority_001')
    decision_old=Decision('Previous decision',person2.id,authority.id,T,id='decision_old')
    decision=Decision('Proceed',person2.id,authority.id,T,id='decision_001')
    permission=Permission(person2.id,'VIEW','work',id='permission_001')
    delegation=Delegation(person.id,person2.id,'REQUEST_QUOTE',id='delegation_001')
    authorization=Authorization(person2.id,'REQUEST_QUOTE','quote',authority.id,person.id,id='authz_001')
    action=Action('REQUEST_QUOTE',person2.id,'supplier_001',authorization.id,id='action_001')
    response=ObservedResponse(action.id,'Received',T,id='response_001')
    validation=Validation(condition.id,person.id,'manual',ValidationResult.SATISFIED,T,id='validation_001',evidence_ids=[evidence.id])
    recovery=Recovery('Recover','work_001',outcome.id,id='recovery_001',evidence_ids=[evidence.id])
    notification=Notification(person.id,'Attention',id='notification_001',related_object_ids=[risk.id])
    meeting=Meeting('Review',T,id='meeting_001',participant_ids=[person.id,person2.id],operational_thread_id=thread.id)
    artifact=Artifact('Quote','email',id='artifact_001',content_ref='artifact://quote',evidence_ids=[evidence.id])
    history=HistoryRecord(work.id,'STATE_CHANGED',T,id='history_001',actor_id=person2.id,prior_state=state_prior.id,resulting_state=state.id,evidence_ids=[evidence.id])
    correction=Correction(claim.id,claim_old.id,claim.id,'source corrected',T,id='correction_001')
    decision_old.envelope=ObjectEnvelope(**{**decision_old.envelope.__dict__,'created_at':T,'recorded_at':T,'validity_status':ValidityStatus.SUPERSEDED})
    decision.envelope=ObjectEnvelope(**{**decision.envelope.__dict__,'created_at':T,'recorded_at':T})
    supersession=Supersession('decision_old',decision.id,'new decision',T,id='supersession_001')
    trace=ProcessingTrace(action.id,id='trace_001',stages=['INPUT','IDENTITY','EVIDENCE','TRUTH','TEMPORAL','CHANGE','CONSEQUENCE','SIGNIFICANCE','RESPONSE','PERMISSION','AUTHORITY','AUTHORIZATION','ACTION','OBSERVATION','VALIDATION','FINAL_STATE'],final_state_ref=validation.id)
    proof=ExecutionProofRecord('exec_001','engine_0.1','fixture_1.0','MODEL-ALL-001','1.0','inputhash','outputhash','PASS','pytest',id='proof_001',trace_id=trace.id)
    return [org,person,person2,role,outcome,condition,thread,resp,work,work2,commitment,obligation,dep,rel,event,evidence,claim_old,claim,truth,state_prior,state,change,consequence,significance,risk,intervention,recommendation,decision_old,decision,permission,authority,delegation,authorization,action,response,validation,recovery,notification,meeting,artifact,history,correction,supersession,trace,proof]
