from enum import Enum

class ObjectStatus(str, Enum):
    ACTIVE="ACTIVE"; INACTIVE="INACTIVE"
class ValidityStatus(str, Enum):
    VALID="VALID"; INVALID="INVALID"; UNCERTAIN="UNCERTAIN"; STALE="STALE"; SUPERSEDED="SUPERSEDED"
class ClaimStatus(str, Enum):
    ESTABLISHED="ESTABLISHED"; SUPPORTED="SUPPORTED"; REPORTED="REPORTED"; INFERRED="INFERRED"; CONFLICTED="CONFLICTED"; UNKNOWN="UNKNOWN"; STALE="STALE"; SUPERSEDED="SUPERSEDED"
class ConsequenceSupport(str, Enum):
    ESTABLISHED="ESTABLISHED"; SUPPORTED="SUPPORTED"; POTENTIAL="POTENTIAL"; UNKNOWN="UNKNOWN"
class InterventionType(str, Enum):
    KNOW="KNOW"; MONITOR="MONITOR"; WAIT="WAIT"; CLARIFY="CLARIFY"; RECOMMEND="RECOMMEND"; REQUEST_DECISION="REQUEST_DECISION"; REQUEST_AUTHORIZATION="REQUEST_AUTHORIZATION"; ACT="ACT"; ADJUST="ADJUST"; NO_INTERVENTION="NO_INTERVENTION"
class ActionStatus(str, Enum):
    PROPOSED="PROPOSED"; AUTHORIZED="AUTHORIZED"; EXECUTING="EXECUTING"; EXECUTED="EXECUTED"; REJECTED="REJECTED"; FAILED="FAILED"
class ValidationResult(str, Enum):
    SATISFIED="SATISFIED"; NOT_SATISFIED="NOT_SATISFIED"; INCONCLUSIVE="INCONCLUSIVE"
class RelationshipType(str, Enum):
    OWNS="OWNS"; DEPENDS_ON="DEPENDS_ON"; ENABLES="ENABLES"; BLOCKS="BLOCKS"; REQUIRES="REQUIRES"; APPROVES="APPROVES"; DELEGATES="DELEGATES"; SUCCEEDS="SUCCEEDS"; REPLACES="REPLACES"; CONFLICTS_WITH="CONFLICTS_WITH"
class LifecycleState(str, Enum):
    DRAFT="DRAFT"; ACTIVE="ACTIVE"; ACKNOWLEDGED="ACKNOWLEDGED"; STARTED="STARTED"; WAITING="WAITING"; BLOCKED="BLOCKED"; ON_HOLD="ON_HOLD"; COMPLETED="COMPLETED"; CANCELLED="CANCELLED"; SUPERSEDED="SUPERSEDED"
